import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { IdleTimer } from "@/components/auth/IdleTimer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Smart Law Office || Deliver legal support, anytime, anywhere.",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IdleTimer />
        {children}
        {/* <Script
          src="https://js.paystack.co/v1/inline.js"
          strategy="lazyOnload"
        /> */}
        <Toaster />
      </body>
    </html>
  );
}
